name: Sync With Upstream Osmosis

on:
  schedule:
    - cron: '38 */3 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    environment: D-Nice-bot
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          owner: osmosis-labs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.DNICEBOT_PAT }}
          auto_approve: true

