name: Deploy to Skynet

on:
  push:
    branches: [master]

jobs:
  build:
    environment: skynet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - uses: c-hive/gha-yarn-cache@v2

      - run: yarn
      - run: yarn build

      - name: 'Deploy to Skynet'
        uses: SkynetLabs/deploy-to-skynet-action@main
        with:
          upload-dir: prod
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}
          try-files: index.html /index.html
